# SPDX-FileCopyrightText: 2022-2025 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "ghafscan"
SPDX-PackageSupplier = "Technology Innovation Institute <https://tii.ae>"
SPDX-PackageDownloadLocation = "https://github.com/tiiuae/ghafscan"

[[annotations]]
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileCopyrightText = "2022-2025 Technology Innovation Institute (TII)"
precedence = "closest"
path = [
  "flake.lock",
  "VERSION",
  "**.csv",
  "**.drawio",
  "**.svg"
]
